tasks:
  - init: mvn install -DskipTests=true
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vscjava.vscode-java-test@0.22.2:ZBznuSuKUJo5X8dZe6b9Nw==
    - GabrielBB.vscode-lombok@1.0.1:IAvPOHnFmUYZpRqErUNAiQ==